### ISSUE TITLE
DFLY limit page

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/documentation#104]
We should introduce a page limits under https://www.dragonflydb.io/docs/managing-dragonfly where we state dragonfly limits in a clear manner. This can include blob size, max number of elements in the array etc.

**Comment by Niennienzz** [comment]
It's a great idea! I think this shows the quality of humility and consistency. There's no silver bullet, but there are better systems. Here's a [good example](https://www.meilisearch.com/docs/learn/advanced/known_limitations) to reference from Meilisearch.

But I need to talk to engineers in order to get a rather complete list of limitations.

**Comment by romange** [comment]
related flags: max_client_iobuf_len, max_multi_bulk_len. Also constants like `kMaxStrLen`
